import { useEffect, useState } from 'react';
import { formatSQL } from '../lib/sqlFormatter';
import { readStoredRules } from '../lib/storage';

export default function FormatterPanel() {
  const [inputSQL, setInputSQL] = useState('');
  const [outputSQL, setOutputSQL] = useState('');
  const [activeTab, setActiveTab] = useState<'input' | 'formatted'>('input');
  const [copied, setCopied] = useState(false);

  useEffect(() => {
    if (!inputSQL.trim()) {
      setOutputSQL('');
      return;
    }

    const rules = readStoredRules();
    if (!rules) return;

    try {
      const formatted = formatSQL(inputSQL, rules);
      setOutputSQL(formatted);
    } catch (error) {
      const message =
        error instanceof Error ? error.message : 'Unknown formatting error.';
      setOutputSQL(`-- Error formatting SQL\n${message}`);
    }
  }, [inputSQL]);

  const handleCopy = async () => {
    if (!outputSQL) return;
    try {
      await navigator.clipboard.writeText(outputSQL);
      setCopied(true);
      setTimeout(() => setCopied(false), 2000);
    } catch {
      const textarea = document.createElement('textarea');
      textarea.value = outputSQL;
      document.body.appendChild(textarea);
      textarea.select();
      document.execCommand('copy');
      document.body.removeChild(textarea);
      setCopied(true);
      setTimeout(() => setCopied(false), 2000);
    }
  };

  return (
    <div className="max-w-[90rem] mx-auto px-4 sm:px-6 lg:px-8 pb-6 animate-slide-up">
      <div className="md:hidden flex p-1.5 bg-slate-200/60 dark:bg-[#111] rounded-2xl mb-6 backdrop-blur-md shadow-inner">
        <button
          onClick={() => setActiveTab('input')}
          className={`flex-1 py-3 text-sm font-bold rounded-xl flex items-center justify-center gap-2 transition-all duration-300 ${activeTab === 'input'
            ? 'bg-white dark:bg-[#222] text-slate-800 dark:text-white shadow-[0_2px_8px_rgba(0,0,0,0.08)]'
            : 'text-slate-500 dark:text-slate-400 hover:text-slate-700 dark:hover:text-slate-200'
            }`}
        >
          Raw AI Output
        </button>
        <button
          onClick={() => setActiveTab('formatted')}
          className={`flex-1 py-3 text-sm font-bold rounded-xl flex items-center justify-center gap-2 transition-all duration-300 ${activeTab === 'formatted'
            ? 'bg-white dark:bg-[#222] text-slate-800 dark:text-white shadow-[0_2px_8px_rgba(0,0,0,0.08)]'
            : 'text-slate-500 dark:text-slate-400 hover:text-slate-700 dark:hover:text-slate-200'
            }`}
        >
          Standardized
        </button>
      </div>

      <div className="glass-panel rounded-2xl overflow-hidden shadow-2xl relative">
        <div className="flex items-center justify-between px-4 py-3 border-b border-slate-200/50 dark:border-white/10 bg-slate-50/50 dark:bg-[#111]">
          <div className="flex items-center gap-2 w-24">
            <div className="w-3 h-3 rounded-full bg-red-400/80"></div>
            <div className="w-3 h-3 rounded-full bg-yellow-400/80"></div>
            <div className="w-3 h-3 rounded-full bg-green-400/80"></div>
          </div>

          <div className="w-24 flex justify-end">
            <button
              onClick={handleCopy}
              disabled={!outputSQL}
              className="flex items-center gap-1.5 px-3 py-1 bg-blue-500/10 hover:bg-blue-500/20 text-blue-600 dark:text-blue-400 disabled:opacity-30 rounded-md transition-colors text-xs font-semibold"
            >
              {copied ? 'Copied!' : 'Copy'}
            </button>
          </div>
        </div>

        <div className="grid grid-cols-1 md:grid-cols-2 divide-y md:divide-y-0 md:divide-x divide-slate-200/50 dark:divide-white/10 h-[65vh] min-h-[500px]">
          <div className={`flex-col h-full bg-white/40 dark:bg-black/40 relative group ${activeTab === 'formatted' ? 'hidden md:flex' : 'flex'}`}>
            <div className="absolute top-3 right-4 z-10 px-2 py-1 rounded-md bg-red-50 dark:bg-red-500/10 border border-red-100 dark:border-red-500/20 text-[10px] font-bold text-red-500 uppercase tracking-widest select-none pointer-events-none">
              Chaotic AI Output
            </div>
            <textarea
              value={inputSQL}
              onChange={(e) => setInputSQL(e.target.value)}
              placeholder="Paste the messy SQL generated by AI here..."
              className="w-full h-full p-6 bg-transparent editor-textarea text-slate-700 dark:text-slate-300 resize-none focus:outline-none placeholder-slate-400/50 dark:placeholder-slate-600/50"
              spellCheck="false"
            />
          </div>

          <div className={`flex-col h-full overflow-hidden bg-slate-50/40 dark:bg-[#0a0a0a]/60 relative ${activeTab === 'input' ? 'hidden md:flex' : 'flex'}`}>
            <div className="absolute top-3 right-4 z-10 px-2 py-1 rounded-md bg-green-50 dark:bg-green-500/10 border border-green-100 dark:border-green-500/20 text-[10px] font-bold text-green-500 uppercase tracking-widest select-none pointer-events-none">
              Your Standard
            </div>
            <div className="w-full h-full min-h-0 p-6 overflow-auto">
              {outputSQL ? (
                <pre className="editor-textarea text-slate-900 dark:text-[#a5d6ff]">{outputSQL}</pre>
              ) : (
                <div className="flex h-full items-center justify-center">
                  <div className="text-center space-y-3">
                    <div className="text-4xl">SQL</div>
                    <p className="text-sm text-slate-400 dark:text-slate-500 font-medium">
                      Formatted standard will appear here.
                    </p>
                  </div>
                </div>
              )}
            </div>
          </div>
        </div>
      </div>

      <div className="absolute top-1/2 left-1/2 -translate-x-1/2 -translate-y-1/2 w-full max-w-4xl h-1/2 bg-blue-500/20 dark:bg-blue-500/10 blur-[100px] pointer-events-none -z-10"></div>
    </div>
  );
}
